FROM node:22

WORKDIR /app
COPY linkout/package*.json ./
RUN npm install

# avoid erasing node_modules by volume mounting
VOLUME [ "/app/node_modules" ]

COPY linkout/ .
# no npm run build

# Expose port 3000 pour hot-reload
EXPOSE 3000

# Lancer le serveur de dev React
CMD ["npm", "run", "dev"]