# build stage
FROM node:22 AS build

WORKDIR /app
COPY linkout/package*.json ./
RUN npm install

COPY linkout/ .
RUN npm run build

# Nginx stage
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]